### ISSUE TITLE
cannot contact TLSv1.3 (web)server from app for info.json

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#158]
It looks like TLSv1.3 does not work from the app to the web server to retrieve info.json, e.g. `https://vpn-next.tuxed.net/info.json`. It _does_ work from Edge. I guess the HTTP library used to interact with the API needs an update to support TLSv1.3.

Tested with 1.0.38 on Windows 10.

```
System.AggregateException: Loading of API endpoints failed. ---> System.AggregateException: Downloading from web failed. Please check your internet connection. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)
   --- End of inner exception stack trace ---
   at eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)
   at eduVPN.Xml.Response.Get(Uri uri, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)
   at eduVPN.Models.Instance.GetEndpoints(CancellationToken ct)
   --- End of inner exception stack trace ---
   at eduVPN.Models.Instance.GetEndpoints(CancellationToken ct)
   at eduVPN.ViewModels.Windows.ConnectWizard.Instance_RequestAuthorization(Object sender, RequestAuthorizationEventArgs e)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at eduVPN.ViewModels.Windows.ConnectWizard.<TriggerAuthorizationAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at eduVPN.ViewModels.Pages.CustomInstancePage.<<get_SelectCustomInstance>b__7_0>d.MoveNext()
---> (Inner Exception #0) System.AggregateException: Downloading from web failed. Please check your internet connection. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)
   --- End of inner exception stack trace ---
   at eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)
   at eduVPN.Xml.Response.Get(Uri uri, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)
   at eduVPN.Models.Instance.GetEndpoints(CancellationToken ct)
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String response_type, CancellationToken ct, Response previous)<---
<---
```

**Comment by fkooman** [comment]
I am sorry if this was already fixed in the 2.x releases, didn't test that yet :cry:

**Comment by fkooman** [comment]
Tested it with 2.x release (1.255.7) just to be complete, and it also doesn't work there.

**Comment by rozmansi** [comment]
This is beyond eduVPN client: we're using WebRequest from .NET Framework. I have updated the .NET version from 4.5 to 4.8, so the TLS 1.3 constants are now defined. But that doesn't mean it changes anything with the Schannel the .NET is using for TLS. According to https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support, the Schannel will support TLS 1.3 in Windows Server 2022?!

**Comment by rozmansi** [comment]
#159 is another reason we might consider using a 3rd party library for HTTPS. Microsoft's support is lagging behind. And even when Microsoft does it, it doesn't do it retroactively. Enforcing TLS 1.3 would permanently leave users of non-bleeding-edge Windows out in the cold.

(BTW: Edge is a rebranded Chrome. It doesn't use system-provided Schannel library for TLS.)
