### ISSUE TITLE
error obtaining certificate/private key

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#68]
vpn.tuxed.net -> 2FA profile

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: Loading of client certificate failed. ---> eduVPN.Models.CertificatePrivateKeyException: Private key is invalid or of unsupported format. ---> System.Security.Cryptography.CryptographicException: Bad Data.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at eduVPN.Models.Certificate.DecodePrivateKeyPKCS8(Byte[] priv_key)
   at eduVPN.Models.Certificate.Load(Object obj)
   --- End of inner exception stack trace ---
   at eduVPN.Models.Certificate.Load(Object obj)
   at eduVPN.Models.Instance.GetClientCertificate(Instance authenticating_instance, CancellationToken ct)
   --- End of inner exception stack trace ---
   at eduVPN.Models.Instance.GetClientCertificate(Instance authenticating_instance, CancellationToken ct)
   at eduVPN.ViewModels.VPN.OpenVPNSession.<.ctor>b__10_2()
   at eduVPN.ViewModels.VPN.VPNSession.<Run>b__63_0(Action action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at eduVPN.ViewModels.VPN.VPNSession.Run()
   at eduVPN.ViewModels.Windows.ConnectWizard.<>c__DisplayClass22_0.<get_StartSession>b__2()
---> (Inner Exception #0) System.AggregateException: Loading of client certificate failed. ---> eduVPN.Models.CertificatePrivateKeyException: Private key is invalid or of unsupported format. ---> System.Security.Cryptography.CryptographicException: Bad Data.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at eduVPN.Models.Certificate.DecodePrivateKeyPKCS8(Byte[] priv_key)
   at eduVPN.Models.Certificate.Load(Object obj)
   --- End of inner exception stack trace ---
   at eduVPN.Models.Certificate.Load(Object obj)
   at eduVPN.Models.Instance.GetClientCertificate(Instance authenticating_instance, CancellationToken ct)
   --- End of inner exception stack trace ---
   at eduVPN.Models.Instance.GetClientCertificate(Instance authenticating_instance, CancellationToken ct)
   at eduVPN.ViewModels.VPN.OpenVPNSession.<.ctor>b__10_2()
   at eduVPN.ViewModels.VPN.VPNSession.<Run>b__63_0(Action action)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
---> (Inner Exception #0) eduVPN.Models.CertificatePrivateKeyException: Private key is invalid or of unsupported format. ---> System.Security.Cryptography.CryptographicException: Bad Data.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at eduVPN.Models.Certificate.DecodePrivateKeyPKCS8(Byte[] priv_key)
   at eduVPN.Models.Certificate.Load(Object obj)
   --- End of inner exception stack trace ---
   at eduVPN.Models.Certificate.Load(Object obj)
   at eduVPN.Models.Instance.GetClientCertificate(Instance authenticating_instance, CancellationToken ct)<---
<---
```

**Comment by rozmansi** [comment]
I couldn't reproduce this issue. Actually, I admit I have noticed it a couple of times in the past few months. Unfortunately, I was not able to recognize a pattern out of it as it happened very rarely. Until you reported it, confirming I was not the only one to experience it...

The underlying .NET Framework Crypto returns _Bad Data_ when the Client tries to import the private key.

Digging into it, I believe I found the cause. .NET Framework has no ASN.1 parser, so I have to decode PKCS#1 and PKCS#8 myself and prepare the RSA private key in the way that .NET Framework understands:

1. modulus, exponent, _d_, _p_, _q_ and the rest of RSA parameters must be MSB byte arrays **with ASN.1 zero padding removed** (all parameters are assumed positive).
2. .NET Framework **expects fixed size RSA parameters**. For 2048bit keys:
   - modulus and _d_ must be exactly 512B wide,
   - _p_, _q_, _dp_, _dq_ and _inverse(q)_ must be exactly 256B wide.

Failure to comply results in a `System.Security.Cryptography.CryptographicException` : _Bad Data_.

While eduVPN Client did remove ASN.1 padding to comply with 1., once every while an RSA parameter can get small enough to get shorter than its full width. In that case, the RSA parameter must actually be `00` padded to comply with 2.
